# Searches for ANTGRAPHICS includes and library files
#
# Sets the variables
#   ANTGRAPHICS_FOUND
#   ANTGRAPHICS_INCLUDE_DIR
#   ANTGRAPHICS_LIBRARY

SET (ANTGRAPHICS_FOUND FALSE)

FIND_PATH (ANTGRAPHICS_INCLUDE_DIR antAbstractApp.h
  /usr/include/antGraphics
  /usr/local/include/antGraphics
  $ENV{HOME}/local/include/antGraphics
)

FIND_LIBRARY (ANTGRAPHICS_LIBRARY NAMES ANTGRAPHICS PATHS
  /usr/lib
  /usr/local/lib
  $ENV{HOME}/local/lib
  )


IF (ANTGRAPHICS_INCLUDE_DIR AND ANTGRAPHICS_LIBRARY)
  SET (ANTGRAPHICS_FOUND TRUE)
ENDIF (ANTGRAPHICS_INCLUDE_DIR AND ANTGRAPHICS_LIBRARY)

IF (ANTGRAPHICS_LIBRARY)
  SET (ANTGRAPHICS_LIBRARIES ${ANTGRAPHICS_LIBRARY})
ENDIF(ANTGRAPHICS_LIBRARY)

MARK_AS_ADVANCED (
  ANTGRAPHICS_INCLUDE_DIR
  ANTGRAPHICS_LIBRARIES
  ANTGRAPHICS_LIBRARY  
)